In [1]:
# import base libraries 

# import geospatial libraries and tools 
import folium

In [2]:

# assign values for latitude and longitude, a global geospatial addressing system, that uniquely identifies a location
latitude = 43.7031000
longitude = -72.28854
map = folium.Map()
marker = folium.Marker(location=[latitude,longitude])
marker.add_to(map)
map

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import geopandas as gpd
import shapely

In [2]:
points_csv = pd.read_csv("https://rcweb.dartmouth.edu/homes/f002d69/workshops/data/bear-sightings.csv")
points_csv.head(3)

   bear.id   longitude   latitude
0        7 -148.956023  62.658220
1       57 -152.622839  58.350642
2       69 -144.937397  62.382270

In [3]:
points = gpd.GeoDataFrame(points_csv, geometry=gpd.points_from_xy(points_csv.longitude, points_csv.latitude))
points.head(2)

   bear.id   longitude   latitude                     geometry
0        7 -148.956023  62.658220  POINT (-148.95602 62.65822)
1       57 -152.622839  58.350642  POINT (-152.62284 58.35064)

In [6]:
# Set the CRS to EPSG 4326, a worldwide coordinate system
#  (https://epsg.io/4326)
points.set_crs(epsg=4326, inplace=True)
# Verify the CRS
print(points.crs)

EPSG:4326